# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-04 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='摘要'),
        ),
    ]
