# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
