# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
