# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180905_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modify_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
